const initialHtml=`<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>云与群星之间</title>
  <meta name="author" content="星海旅人">
  <meta name="category" content="幻想文学">
  <meta name="description" content="一场穿越云海与群星的旅程">
  <style>
    body{max-width:760px;margin:0 auto;padding:56px 64px;color:#28231d;background:#faf6ed;font:17px/1.9 Georgia,"Songti SC",serif}
    h1{text-align:center;font-size:36px}h2{margin-top:48px}.hero{height:260px;background:url('assets/cloud-realm-study-v2.png') center/cover;border-radius:4px}
  </style>
</head>
<body>
  <h1>云与群星之间</h1>
  <p style="text-align:center">星海旅人</p>
  <div class="hero"></div>
  <h2>第一章 云海之上</h2>
  <p>在很久以前，天空并不只是天空，而是一片流动的海洋。无数岛屿悬浮在云海之上，彼此通过光的桥梁相连。</p>
</body>
</html>`;

const state={
  mode:'manual',
  bookMeta:{title:'云与群星之间',author:'星海旅人',category:'幻想文学',description:'一场穿越云海与群星的旅程',tags:['奇幻','世界观','冒险'],status:'draft',coverUrl:''},
  htmlContent:initialHtml,previewHtml:initialHtml,validationResult:{},splitRatio:65,previewDevice:'desktop',isFullscreenPreview:false,mobilePane:'edit',
  importMeta:{fileName:'',structure:'等待导入',duplicate:'暂未启用'},prompt:''
};

const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const metaValue=(doc,name)=>doc.querySelector(`meta[name="${name}"]`)?.getAttribute('content')?.trim()||'';

function parseHtml(html,{apply=true}={}){
  const doc=new DOMParser().parseFromString(html,'text/html');
  const found={title:doc.querySelector('title')?.textContent?.trim()||'',author:metaValue(doc,'author'),category:metaValue(doc,'category'),description:metaValue(doc,'description'),tags:metaValue(doc,'keywords').split(',').map(x=>x.trim()).filter(Boolean)};
  if(apply){['title','author','category','description'].forEach(k=>{if(found[k])state.bookMeta[k]=found[k]});if(found.tags.length)state.bookMeta.tags=found.tags}
  state.validationResult={title:Boolean(found.title||state.bookMeta.title),author:Boolean(found.author||state.bookMeta.author),category:Boolean(found.category||state.bookMeta.category),html:Boolean(doc.documentElement&&doc.body&&!doc.querySelector('parsererror')),cover:Boolean(state.bookMeta.coverUrl)};
  return found;
}

function WorkshopHeader(){return `<header class="workshop-header"><div><span class="workshop-kicker">CONTENT CREATION DESK</span><h1>AI 工坊</h1><p>创建、生成并导入你的书籍内容</p></div><blockquote>所有伟大的故事，<br>都从一个念头开始。</blockquote></header>`}
function WorkshopStats(){return `<section class="workshop-stats" aria-label="工作台概览"><div><i>◇</i><span><small>模板数量</small><b>12</b></span></div><div><i>▤</i><span><small>待导入</small><b>3</b></span></div><div><i>▥</i><span><small>本周创建</small><b>5</b></span></div><button disabled><i>▧</i><span><small>生成记录　<em>开发中</em></small><b>暂不可用</b></span></button></section>`}
function CreationModeTabs(){const tabs=[['ai','✦','AI 直接生成'],['manual','▤','手动创建书籍'],['import','⇧','导入 HTML']];return `<nav class="creation-tabs" aria-label="创建模式">${tabs.map(([id,ic,label])=>`<button data-creation-mode="${id}" class="${state.mode===id?'active':''}"><i>${ic}</i><span>${label}</span>${id==='ai'?'<em>开发中</em>':''}</button>`).join('')}</nav>`}

function BookMetaForm({compact=false}={}){return `<section class="meta-form ${compact?'compact':''}"><header><span>▣</span><div><h2>书籍基本信息</h2><p>${compact?'检查并修改自动识别的结果':'填写核心元信息，方便整理与管理'}</p></div></header><div class="meta-grid"><label><b>书名 <em>*</em></b><input data-meta="title" value="${esc(state.bookMeta.title)}" placeholder="请输入书名"></label><label><b>作者</b><input data-meta="author" value="${esc(state.bookMeta.author)}" placeholder="请输入作者"></label><label><b>分类</b><select data-meta="category">${['幻想文学','科幻宇宙','文学经典','哲学思想','历史人文','其他'].map(x=>`<option ${x===state.bookMeta.category?'selected':''}>${x}</option>`).join('')}</select></label><label class="description-field"><b>简介</b><input data-meta="description" value="${esc(state.bookMeta.description)}" placeholder="可选"></label><div class="tag-field"><b>标签</b><div class="editable-tags">${state.bookMeta.tags.map((x,i)=>`<button data-remove-tag="${i}" title="删除标签">${esc(x)}　×</button>`).join('')}<button class="add-tag" data-add-tag>＋ 添加标签</button></div></div><div class="status-field"><b>状态</b><label><input type="radio" name="workshop-status" value="draft" ${state.bookMeta.status==='draft'?'checked':''}> 草稿</label><label><input type="radio" name="workshop-status" value="published" ${state.bookMeta.status==='published'?'checked':''}> 已发布</label></div>${compact?'':`<div class="cover-field"><b>封面（可选）</b><label class="cover-picker"><input id="coverInput" type="file" accept="image/png,image/jpeg,image/webp"><span class="cover-preview" id="coverPreview" ${state.bookMeta.coverUrl?`style="background-image:url('${state.bookMeta.coverUrl}')"`:''}>${state.bookMeta.coverUrl?'':'▧<small>选择本地图片</small>'}</span></label><small>仅在浏览器中预览，不会上传服务器</small></div>`}</div></section>`}

function HtmlEditor(){const lines=Math.max(1,state.htmlContent.split('\n').length);return `<section class="html-editor-panel"><header><div><h2>&lt;/&gt;　HTML 内容</h2><p>支持完整 HTML，预览在隔离环境中运行</p></div><div class="editor-tools"><button data-paste-html>粘贴完整 HTML</button><button data-recognize>从 HTML 识别信息</button><button data-format>格式化</button></div></header><div class="html-editor-shell"><pre class="editor-lines" id="editorLines">${Array.from({length:lines},(_,i)=>i+1).join('\n')}</pre><textarea id="workshopHtml" spellcheck="false" aria-label="HTML 内容">${esc(state.htmlContent)}</textarea></div></section>`}
function ManualCreatePanel(){return `<div class="manual-create-panel">${BookMetaForm()}${HtmlEditor()}</div>`}

function ImportHtmlPanel(){return `<section class="import-panel"><header><h2>导入 HTML</h2><p>选择一种方式导入，系统会在本地解析并显示识别结果。</p></header><label class="drop-zone" id="dropZone"><input id="htmlFileInput" type="file" accept=".html,.htm,text/html"><span>⇧</span><b>拖入 HTML 文件</b><small>或点击选择文件</small></label><div class="import-or"><span>或</span></div><label class="paste-import"><b>粘贴 HTML</b><textarea id="importHtmlText" placeholder="在这里粘贴完整 HTML…">${state.importMeta.fileName?'':esc(state.htmlContent)}</textarea><button data-parse-paste>解析粘贴内容</button></label><div class="recognized-result ${state.importMeta.structure==='等待导入'?'waiting':''}"><header><h3>识别结果</h3><span>${esc(state.importMeta.fileName||'尚未选择文件')}</span></header>${BookMetaForm({compact:true})}<dl><div><dt>文件名</dt><dd>${esc(state.importMeta.fileName||'—')}</dd></div><div><dt>HTML 结构状态</dt><dd>${esc(state.importMeta.structure)}</dd></div><div><dt>重复检测</dt><dd>${esc(state.importMeta.duplicate)}</dd></div></dl></div></section>`}

function makePrompt(){return `请为《${state.bookMeta.title||'未命名书籍'}》生成一份结构清晰的 HTML 书籍内容。\n作者：${state.bookMeta.author||'未填写'}\n分类：${state.bookMeta.category||'未填写'}\n包含模块：书籍简介、十分钟速读、核心观点、关键概念、延伸阅读。\n输出要求：仅输出完整、语义化的 HTML，包含 title 以及 author、category、description 元信息。`}
function AiGeneratePanel(){return `<section class="ai-panel"><span class="dev-badge">开发中</span><header><h2>AI 直接生成</h2><p>配置内容信息并生成标准 Prompt。</p></header><div class="ai-form"><label><b>书名</b><input data-meta="title" value="${esc(state.bookMeta.title)}"></label><label><b>作者</b><input data-meta="author" value="${esc(state.bookMeta.author)}"></label><label><b>分类</b><select data-meta="category"><option>${esc(state.bookMeta.category)}</option><option>幻想文学</option><option>科幻宇宙</option></select></label><label><b>模板</b><select><option>标准书籍内容</option></select></label><label><b>输出格式</b><input value="HTML" disabled></label></div><fieldset><legend>可选模块</legend>${['书籍简介','十分钟速读','核心观点','关键概念','延伸阅读'].map(x=>`<label><input type="checkbox" checked> ${x}</label>`).join('')}</fieldset><div class="ai-notice"><b>当前版本暂未接入 AI 自动生成能力。</b><p>你可以先生成标准 Prompt，复制到 ChatGPT，再将生成结果粘贴或导入到 AI 工坊。</p></div><div class="prompt-output" id="promptOutput">${esc(state.prompt)}</div><footer><button data-generate-prompt>生成 Prompt</button><button data-copy-prompt>复制 Prompt</button><button class="primary" data-ai-generate>生成内容</button></footer></section>`}

function ValidationList(){const v=state.validationResult;const items=[['title','书名识别成功'],['author','作者识别成功'],['category','分类识别成功'],['html','HTML 结构正常']];return `<section class="validation-list"><header><h3>内容校验结果</h3><button data-revalidate>重新校验</button></header>${items.map(([key,label])=>`<div class="${v[key]?'valid':'muted'}"><i>${v[key]?'✓':'—'}</i><span>${label}</span></div>`).join('')}<div class="warning"><i>!</i><span>${v.cover?'封面已选择':'封面建议确认'}</span></div></section>`}
function QuickPreviewPanel(){return `<aside class="quick-preview" data-workshop-pane="preview"><header><div><h2>快速预览</h2><p>用于确认页面结构与内容，不作为完整阅读页</p></div><span>隔离预览</span></header><div class="preview-thumb"><iframe id="quickPreviewFrame" sandbox="" title="书籍快速预览"></iframe></div>${ValidationList()}<div class="preview-actions"><button data-fullscreen>全屏预览</button><button data-save>保存草稿</button><button class="primary" data-publish>发布</button></div></aside>`}
function DevicePreviewSwitch(){return `<div class="device-switch">${[['desktop','桌面'],['tablet','平板'],['mobile','手机']].map(([id,label])=>`<button data-device="${id}" class="${state.previewDevice===id?'active':''}">${label}</button>`).join('')}</div>`}
function FullscreenPreviewOverlay(){return `<section class="fullscreen-preview" id="fullscreenPreview" hidden><header><button data-close-fullscreen>← 返回编辑</button>${DevicePreviewSwitch()}<div><button data-save>保存草稿</button><button class="primary" data-publish>发布</button></div></header><main><div class="device-frame ${state.previewDevice}" id="deviceFrame"><iframe id="fullscreenPreviewFrame" sandbox="" title="书籍全屏预览"></iframe></div></main></section>`}
function ResizableSplitPane(){return `<div class="responsive-pane-tabs"><button class="${state.mobilePane==='edit'?'active':''}" data-mobile-pane="edit">编辑</button><button class="${state.mobilePane==='preview'?'active':''}" data-mobile-pane="preview">预览</button></div><section class="split-pane ${state.mobilePane==='preview'?'show-preview':'show-editor'}" id="splitPane" style="--editor-fr:${state.splitRatio}fr;--preview-fr:${100-state.splitRatio}fr"><div class="editor-pane" data-workshop-pane="edit"><div class="creation-panel-slot"></div></div><button class="split-handle" id="splitHandle" title="拖动调整宽度，双击恢复默认" aria-label="调整编辑区和预览区宽度"><i></i></button>${QuickPreviewPanel()}</section>`}
function AiWorkshopPage(){return `<div class="ai-workshop-page">${WorkshopHeader()}${WorkshopStats()}<section class="workshop-surface">${CreationModeTabs()}${ResizableSplitPane()}</section>${FullscreenPreviewOverlay()}</div>`}

function formatHtml(html){return html.replace(/>\s*</g,'>\n<').split('\n').reduce((out,line)=>{line=line.trim();if(/^<\//.test(line))out.level=Math.max(0,out.level-1);out.lines.push('  '.repeat(out.level)+line);if(/^<[^!/][^>]*[^/]>$/.test(line)&&!/<\/(?:[^>]+)>$/.test(line)&&!/^<(meta|link|img|input|br|hr)\b/i.test(line))out.level++;return out},{level:0,lines:[]}).lines.join('\n')}

export function createAiWorkshopPage(root,{showToast,bindNavigation}){
  parseHtml(state.htmlContent,{apply:false});root.innerHTML=AiWorkshopPage();bindNavigation?.();
  const slot=root.querySelector('.creation-panel-slot');
  const updatePreview=()=>{state.previewHtml=state.htmlContent;const quick=root.querySelector('#quickPreviewFrame');if(quick)quick.srcdoc=state.previewHtml;const full=root.querySelector('#fullscreenPreviewFrame');if(full)full.srcdoc=state.previewHtml;const validation=root.querySelector('.validation-list');if(validation)validation.outerHTML=ValidationList();bindSharedActions()};
  const bindMeta=()=>{root.querySelectorAll('[data-meta]').forEach(input=>input.addEventListener('input',()=>{state.bookMeta[input.dataset.meta]=input.value}));root.querySelectorAll('input[name="workshop-status"]').forEach(input=>input.addEventListener('change',()=>state.bookMeta.status=input.value));root.querySelectorAll('[data-remove-tag]').forEach(btn=>btn.addEventListener('click',()=>{state.bookMeta.tags.splice(Number(btn.dataset.removeTag),1);renderMode()}));root.querySelector('[data-add-tag]')?.addEventListener('click',()=>{const value=prompt('输入新标签');if(value?.trim()){state.bookMeta.tags.push(value.trim());renderMode()}});const cover=root.querySelector('#coverInput');cover?.addEventListener('change',()=>{const file=cover.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{state.bookMeta.coverUrl=reader.result;renderMode();updatePreview()};reader.readAsDataURL(file)})};
  const importContent=(html,fileName='粘贴内容.html')=>{state.htmlContent=html;state.previewHtml=html;state.importMeta.fileName=fileName;const found=parseHtml(html);state.importMeta.structure=state.validationResult.html?'结构正常':'结构异常';renderMode();updatePreview();showToast(`已解析 ${fileName}`);return found};
  const bindManual=()=>{bindMeta();const editor=root.querySelector('#workshopHtml');const lines=root.querySelector('#editorLines');editor.addEventListener('input',()=>{state.htmlContent=editor.value;state.previewHtml=editor.value;lines.textContent=Array.from({length:Math.max(1,editor.value.split('\n').length)},(_,i)=>i+1).join('\n');updatePreview()});root.querySelector('[data-recognize]').addEventListener('click',()=>{parseHtml(state.htmlContent);renderMode();updatePreview();showToast('已尝试从 HTML 识别信息')});root.querySelector('[data-format]').addEventListener('click',()=>{state.htmlContent=formatHtml(state.htmlContent);renderMode();updatePreview();showToast('HTML 已格式化')});root.querySelector('[data-paste-html]').addEventListener('click',async()=>{try{const text=await navigator.clipboard.readText();if(text){state.htmlContent=text;renderMode();updatePreview();showToast('已粘贴剪贴板 HTML')}}catch{showToast('请直接在编辑器中粘贴 HTML')}})};
  const bindImport=()=>{bindMeta();const zone=root.querySelector('#dropZone'),fileInput=root.querySelector('#htmlFileInput'),paste=root.querySelector('#importHtmlText');const read=file=>{if(!file)return;const reader=new FileReader();reader.onload=()=>importContent(String(reader.result),file.name);reader.readAsText(file)};fileInput.addEventListener('change',()=>read(fileInput.files?.[0]));['dragenter','dragover'].forEach(name=>zone.addEventListener(name,e=>{e.preventDefault();zone.classList.add('dragging')}));['dragleave','drop'].forEach(name=>zone.addEventListener(name,e=>{e.preventDefault();zone.classList.remove('dragging')}));zone.addEventListener('drop',e=>read(e.dataTransfer?.files?.[0]));root.querySelector('[data-parse-paste]').addEventListener('click',()=>importContent(paste.value));paste.addEventListener('input',()=>{state.htmlContent=paste.value;state.previewHtml=paste.value;updatePreview()})};
  const bindAi=()=>{bindMeta();root.querySelector('[data-generate-prompt]').addEventListener('click',()=>{state.prompt=makePrompt();root.querySelector('#promptOutput').textContent=state.prompt;showToast('Prompt 已生成')});root.querySelector('[data-copy-prompt]').addEventListener('click',async()=>{if(!state.prompt)state.prompt=makePrompt();try{await navigator.clipboard.writeText(state.prompt);showToast('Prompt 已复制')}catch{showToast('复制失败，请手动复制')}});root.querySelector('[data-ai-generate]').addEventListener('click',()=>showToast('当前版本暂未接入 AI 自动生成能力'))};
  const renderMode=()=>{slot.innerHTML=state.mode==='manual'?ManualCreatePanel():state.mode==='import'?ImportHtmlPanel():AiGeneratePanel();if(state.mode==='manual')bindManual();else if(state.mode==='import')bindImport();else bindAi()};
  root.querySelectorAll('[data-creation-mode]').forEach(btn=>btn.addEventListener('click',()=>{state.mode=btn.dataset.creationMode;root.querySelectorAll('[data-creation-mode]').forEach(x=>x.classList.toggle('active',x===btn));renderMode()}));
  const openFullscreen=()=>{state.isFullscreenPreview=true;const overlay=root.querySelector('#fullscreenPreview');overlay.hidden=false;root.querySelector('#fullscreenPreviewFrame').srcdoc=state.previewHtml;document.body.classList.add('preview-open')};
  const closeFullscreen=()=>{state.isFullscreenPreview=false;root.querySelector('#fullscreenPreview').hidden=true;document.body.classList.remove('preview-open')};
  const bindSharedActions=()=>{root.querySelectorAll('[data-fullscreen]').forEach(btn=>btn.onclick=openFullscreen);root.querySelectorAll('[data-close-fullscreen]').forEach(btn=>btn.onclick=closeFullscreen);root.querySelectorAll('[data-save]').forEach(btn=>btn.onclick=()=>showToast('草稿已保存到当前浏览器会话'));root.querySelectorAll('[data-publish]').forEach(btn=>btn.onclick=()=>showToast('发布按钮已就绪，等待接入后端'));root.querySelectorAll('[data-revalidate]').forEach(btn=>btn.onclick=()=>{parseHtml(state.htmlContent,{apply:false});updatePreview();showToast('校验已更新')})};
  bindSharedActions();renderMode();updatePreview();
  root.querySelectorAll('[data-mobile-pane]').forEach(btn=>btn.addEventListener('click',()=>{state.mobilePane=btn.dataset.mobilePane;root.querySelectorAll('[data-mobile-pane]').forEach(x=>x.classList.toggle('active',x===btn));const pane=root.querySelector('#splitPane');pane.classList.toggle('show-preview',state.mobilePane==='preview');pane.classList.toggle('show-editor',state.mobilePane==='edit')}));
  root.querySelectorAll('[data-device]').forEach(btn=>btn.addEventListener('click',()=>{state.previewDevice=btn.dataset.device;root.querySelectorAll('[data-device]').forEach(x=>x.classList.toggle('active',x===btn));root.querySelector('#deviceFrame').className=`device-frame ${state.previewDevice}`}));
  const pane=root.querySelector('#splitPane'),handle=root.querySelector('#splitHandle');let dragging=false;handle.addEventListener('pointerdown',e=>{dragging=true;handle.setPointerCapture(e.pointerId);document.body.classList.add('resizing')});handle.addEventListener('pointermove',e=>{if(!dragging||matchMedia('(max-width:1199px)').matches)return;const box=pane.getBoundingClientRect();state.splitRatio=Math.min(72,Math.max(50,((e.clientX-box.left)/box.width)*100));pane.style.setProperty('--editor-fr',`${state.splitRatio}fr`);pane.style.setProperty('--preview-fr',`${100-state.splitRatio}fr`)});handle.addEventListener('pointerup',()=>{dragging=false;document.body.classList.remove('resizing')});handle.addEventListener('dblclick',()=>{state.splitRatio=65;pane.style.setProperty('--editor-fr','65fr');pane.style.setProperty('--preview-fr','35fr')});
  if(!window.__workshopEscapeBound){window.__workshopEscapeBound=true;window.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.isFullscreenPreview){state.isFullscreenPreview=false;document.querySelector('#fullscreenPreview')?.setAttribute('hidden','');document.body.classList.remove('preview-open')}})}
}
