export const seasonOneChronicles = [
  {
    id: 'season-01-record-001', seasonId: 'season-01', seasonTitle: '云海之外', chapterId: 'chapter-01', chapterTitle: '异常云层', recordNumber: 1,
    type: 'voyage_log', title: '七日不散的云', subtitle: '第 17 日 · 西北航线',
    excerpt: '我已经连续七天看见那片云没有移动。',
    content: '我已经连续七天看见那片云没有移动。船员都说那只是高空错觉，可我们向西北走了四百海里，它仍停在左舷同一角度。昨夜三更，值班水手叫醒我：云层背后有一盏灯，亮了不到半刻。今晨测风索完好，气压却比昨日低了许多。我让轮机舱节省燃料，先沿云缘再走一天。',
    author: '航行者 E.', recordDate: '第 17 日', discoverLocation: '异世界航行图', triggerType: 'first_visit',
    triggerConfig: { type: 'first_visit', page: 'world', firstOnly: true }, coordinates: { x: 34.2, y: 47.6 }, regionId: 'cloud-sea-west', soundId: 'paper', isHidden: false,
  },
  {
    id: 'season-01-record-002', seasonId: 'season-01', seasonTitle: '云海之外', chapterId: 'chapter-01', chapterTitle: '异常云层', recordNumber: 2,
    type: 'adventure_log', title: '偏离航线', subtitle: '第 19 日 · 西北偏北',
    excerpt: '罗盘在午后第一次偏转，船却没有改变航向。',
    content: '午后两点，主罗盘突然向北偏了十一度，备用罗盘却指向西南。舵手以远山和日影复核，确认飞艇并未转向。我们停机漂航二十分钟，指针仍缓慢摆动，像在追逐云层里的某个位置。机械师拆开铜壳，没有发现松动或磁石碎裂。我把异常刻度记在航图边缘，并命令今晚只开半速。',
    author: '航行者 E.', recordDate: '第 19 日', discoverLocation: '旅者手记', triggerType: 'page_visit',
    triggerConfig: { type: 'page_visit', page: 'journal', requiresRecordNumber: 1 }, coordinates: null, regionId: 'cloud-sea-west', soundId: 'archive', isHidden: false,
  },
  {
    id: 'season-01-record-003', seasonId: 'season-01', seasonTitle: '云海之外', chapterId: 'chapter-01', chapterTitle: '异常云层', recordNumber: 3,
    type: 'map_annotation', title: '不存在的坐标', subtitle: '旧航图第六版 · 边缘批注',
    excerpt: '旧世界地图在这里留出了一块不自然的空白。',
    content: '雨水迫使我们整理舱内物资时，我在备用箱底找到一张旧世界地图。纸张属于第六版，西北航线却被人用刀刮去一块，恰好覆盖罗盘异常的坐标。刮痕很旧，背面还有铅笔压印：继续向北时，不要相信第二次日出。地图员认为这句话没有测绘意义，但他仍把压印拓了下来。',
    author: '地图员 洛德', recordDate: '第 21 日', discoverLocation: '雨中的书房', triggerType: 'weather',
    triggerConfig: { type: 'weather', weather: 'rain', requiresRecordNumber: 2 }, coordinates: { x: 39.5, y: 42.1 }, regionId: 'old-route-northwest', soundId: 'rain', isHidden: false,
  },
  {
    id: 'season-01-record-004', seasonId: 'season-01', seasonTitle: '云海之外', chapterId: 'chapter-02', chapterTitle: '残缺星图', recordNumber: 4,
    type: 'ancient_fragment', title: '驿站里的星图', subtitle: '第 24 日 · 无名补给站',
    excerpt: '废弃驿站没有燃料，却留下了一张被烟熏黑的星图。',
    content: '入夜后，我们降落在一座标记为废弃的补给站。蓄水槽已经干涸，仓库里只剩三袋结块的盐和一只损坏的高度计。值班室墙后夹着半张星图，边缘被火烤焦，中央画着一条穿过云海的短线。奇怪的是，线旁记录的不是星位，而是不同高度的风速和气压。',
    author: '航行者 E.', recordDate: '第 24 日', discoverLocation: '深夜书房', triggerType: 'time_period',
    triggerConfig: { type: 'time_period', period: 'night', requiresRecordNumber: 3 }, coordinates: { x: 46.8, y: 36.4 }, regionId: 'abandoned-relay', soundId: 'wind', isHidden: false,
  },
  {
    id: 'season-01-record-005', seasonId: 'season-01', seasonTitle: '云海之外', chapterId: 'chapter-02', chapterTitle: '残缺星图', recordNumber: 5,
    type: 'observation', title: '被改写的北方', subtitle: '星图检视记录',
    excerpt: '墨线覆盖了原有刻度，却没能遮住纸背的针孔。',
    content: '我把星图铺在阅读桌上，用斜光检查。北方三组刻度曾被人为改写，墨色比纸张年轻至少二十年。每个新刻度下方都有细小针孔，连起来正好形成一条缓慢抬升的航线。若按它飞行，燃料会在抵达前耗尽；除非途中确实存在一处未登记的补给点。',
    author: '观测员 米娅', recordDate: '第 26 日', discoverLocation: '阅读空间', triggerType: 'page_visit',
    triggerConfig: { type: 'page_visit', page: 'reading', requiresRecordNumber: 4 }, coordinates: null, regionId: 'abandoned-relay', soundId: 'paper', isHidden: false,
  },
  {
    id: 'season-01-record-006', seasonId: 'season-01', seasonTitle: '云海之外', chapterId: 'chapter-02', chapterTitle: '残缺星图', recordNumber: 6,
    type: 'archive_record', title: '北境档案摘录', subtitle: '馆藏编号 B-204',
    excerpt: '云海之上仍有灯火，但没有一条获准航线通往那里。',
    content: '北境档案 B-204：过去三十七年，共有九艘商船报告在雨夜看见高于云顶的固定灯火。报告中的方位彼此接近，但测得高度差异极大。调查员曾派出两艘轻艇，第一艘因结冰返航，第二艘的升降翼在途中损坏。结论栏只有一行：云海之上仍有灯火，但没有一条获准航线通往那里。',
    author: '北境航务档案馆', recordDate: '旧历 2147 年', discoverLocation: '雨夜', triggerType: 'world_state',
    triggerConfig: { type: 'world_state', weather: 'rain', period: 'night', requiresRecordNumber: 5 }, coordinates: null, regionId: 'northern-archive', soundId: 'archive', isHidden: false,
  },
  {
    id: 'season-01-record-007', seasonId: 'season-01', seasonTitle: '云海之外', chapterId: 'chapter-03', chapterTitle: '云海之外', recordNumber: 7,
    type: 'voyage_log', title: '结冰的升降翼', subtitle: '第 31 日 · 高度 6,200',
    excerpt: '雪在翼面结成薄壳，我们不得不抛下两箱补给。',
    content: '清晨开始降雪，升降翼前缘很快结成薄壳。机械师用热水和帆布清理了三次，右侧拉索仍失去四分之一行程。为了继续爬升，我们抛下两箱备用木料和一桶淡水，只保留七天干粮。云层上方出现一条平直的暗影，持续了约十分钟，随后被雪幕遮住。',
    author: '航行者 E.', recordDate: '第 31 日', discoverLocation: '雪中的露台', triggerType: 'weather',
    triggerConfig: { type: 'weather', weather: 'snow', requiresRecordNumber: 6 }, coordinates: { x: 55.4, y: 29.8 }, regionId: 'upper-cloud-front', soundId: 'wind', isHidden: false,
  },
  {
    id: 'season-01-record-008', seasonId: 'season-01', seasonTitle: '云海之外', chapterId: 'chapter-03', chapterTitle: '云海之外', recordNumber: 8,
    type: 'lost_letter', title: '给留在港口的人', subtitle: '未寄出的信',
    excerpt: '如果我们没有回来，请别把原因归给风暴。',
    content: '如果我们没有回来，请别把原因归给风暴。船体还能支撑，补给也经过重新核算。真正让我不安的是那些灯：每当我们改变航向，它们总会提前出现在新的正前方。船员已经连续两夜没有争吵，大家只是反复检查绳结。明天越过云脊后，我会决定是否返航。',
    author: '航行者 E.', recordDate: '第 34 日', discoverLocation: '天空城首页', triggerType: 'first_visit',
    triggerConfig: { type: 'first_visit', page: 'home', firstOnly: true, requiresRecordNumber: 7 }, coordinates: null, regionId: 'upper-cloud-front', soundId: 'paper', isHidden: false,
  },
  {
    id: 'season-01-record-009', seasonId: 'season-01', seasonTitle: '云海之外', chapterId: 'chapter-03', chapterTitle: '云海之外', recordNumber: 9,
    type: 'observation', title: '冬至高度记录', subtitle: '第 36 日 · 日照最短时',
    excerpt: '短日的最后一道光照出了云层之上的石质轮廓。',
    content: '冬至的日照比预计短了十一分钟。黄昏前，云面裂开一道狭缝，我们看见远处并非山峰，而是一段垂直石壁。它的下缘没有连接地面，几棵高树却从石壁顶部伸出。测距仪镜片破裂，无法得到可靠距离。我只在航图上画下轮廓，没有写名称。',
    author: '观测员 米娅', recordDate: '冬至', discoverLocation: '冬至航线', triggerType: 'date',
    triggerConfig: { type: 'date', date: '12-21', requiresRecordNumber: 8 }, coordinates: { x: 63.1, y: 25.2 }, regionId: 'sky-city-approach', soundId: 'bell', isHidden: false,
  },
  {
    id: 'season-01-record-010', seasonId: 'season-01', seasonTitle: '云海之外', chapterId: 'chapter-03', chapterTitle: '云海之外', recordNumber: 10,
    type: 'adventure_log', title: '第一次看见那座城', subtitle: '第 38 日 · 云脊以东',
    excerpt: '云散开时，整座城市悬在比我们更高的地方。',
    content: '上午九点，风突然停了。云脊从中央缓慢分开，露出一座建在浮岩上的城市，位置比飞艇高约八百米。我们能看见玻璃温室、细长塔楼和沿崖修筑的露台，却没有看见港口信号。主机尚有三成燃料，足够靠近一次，也只够返航一次。船员投票后决定继续。',
    author: '航行者 E.', recordDate: '第 38 日', discoverLocation: '异世界航行图', triggerType: 'page_visit',
    triggerConfig: { type: 'page_visit', page: 'world', requiresRecordNumber: 9 }, coordinates: { x: 68.7, y: 21.9 }, regionId: 'sky-city', soundId: 'wind', isHidden: false,
  },
  {
    id: 'season-01-record-011', seasonId: 'season-01', seasonTitle: '云海之外', chapterId: 'chapter-03', chapterTitle: '云海之外', recordNumber: 11,
    type: 'map_annotation', title: '最后的靠近航线', subtitle: '第 41 日 · 手绘航图',
    excerpt: '进入云墙后，每一次转向都必须依靠灯塔而不是罗盘。',
    content: '靠近航线记在此页背面：从断裂石柱向东四度，保持高度七千二百，直到看见三盏纵向排列的灯。不要跟随罗盘，它会把船带回云墙。左侧气囊已有漏点，每小时需补气一次。若云层再次合拢，就在原地等待，不要下降；下方没有可供迫降的地形。',
    author: '舵手 卡尔', recordDate: '第 41 日', discoverLocation: '多云航线', triggerType: 'weather',
    triggerConfig: { type: 'weather', weather: 'cloudy', requiresRecordNumber: 10 }, coordinates: { x: 72.3, y: 19.4 }, regionId: 'sky-city-gate', soundId: 'archive', isHidden: false,
  },
  {
    id: 'season-01-record-012', seasonId: 'season-01', seasonTitle: '云海之外', chapterId: 'chapter-03', chapterTitle: '云海之外', recordNumber: 12,
    type: 'archive_record', title: '记录缺失', subtitle: '第 43 日 · 回收页',
    excerpt: '我终于抵达那座城。只有一盏灯还亮着。',
    content: '第 43 日。\n\n我终于抵达那座城。城里没有军队，没有市集，也没有王座。停泊台积着很薄的灰，像很久没有船来过。温室里仍有水沿铜管流动，走廊尽头只有一盏灯还亮着。\n\n……\n\n奇怪。\n\n那个人似乎早就知道我会来。\n\n【后续页面缺失】',
    author: '航行者 E.', recordDate: '第 43 日', discoverLocation: '云天幻境', triggerType: 'manual',
    triggerConfig: { type: 'manual', requiresRecordNumber: 11 }, coordinates: { x: 75.1, y: 17.8 }, regionId: 'cloud-realm', soundId: 'bell', isHidden: false,
  },
] as const;
